ShopHungVuong.Web/Controllers/Products1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataAccess;
using DataAccess.Models;
using ShopHungVuong.Web.Models;

namespace ShopHungVuong.Web.Controllers
{
    public class Products1Controller : Controller
    {
        private DataContext db = new DataContext();

        // GET: Products1
        public ActionResult Index()
        {
            if (Session["userID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            var products = db.Products.Include(p => p.GuaranteeProduct).Include(p => p.Manufacturer).Include(p => p.ProductGroup).Include(p => p.Promotion);
            return View(products.ToList());
        }

        // GET: Products1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products1/Create
        public ActionResult Create()
        {
            ViewBag.GuaranteeProductId = new SelectList(db.GuaranteeProducts, "GuaranteeProductId", "Description");
            ViewBag.ManufacturerId = new SelectList(db.Manufacturers, "ManufacturerId", "Name");
            ViewBag.ProductGroupId = new SelectList(db.ProductGroups, "ProductGroupId", "Name");
            ViewBag.PromotionId = new SelectList(db.Promotions, "PromotionId", "Name");
            return View();
        }

        // POST: Products1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductId,Name,Description,ImportPrice,Price,Status,MainPhoto1,MainPhoto2,MainPhoto3,SecondaryPhoto1,SecondaryPhoto2,SecondaryPhoto3,CreatedDate,Color,Amount,Point,ProductGroupId,GuaranteeProductId,PromotionId,ManufacturerId")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.GuaranteeProductId = new SelectList(db.GuaranteeProducts, "GuaranteeProductId", "Description", product.GuaranteeProductId);
            ViewBag.ManufacturerId = new SelectList(db.Manufacturers, "ManufacturerId", "Name", product.ManufacturerId);
            ViewBag.ProductGroupId = new SelectList(db.ProductGroups, "ProductGroupId", "Name", product.ProductGroupId);
            ViewBag.PromotionId = new SelectList(db.Promotions, "PromotionId", "Name", product.PromotionId);
            return View(product);
        }

        // GET: Products1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.GuaranteeProductId = new SelectList(db.GuaranteeProducts, "GuaranteeProductId", "Description", product.GuaranteeProductId);
            ViewBag.ManufacturerId = new SelectList(db.Manufacturers, "ManufacturerId", "Name", product.ManufacturerId);
            ViewBag.ProductGroupId = new SelectList(db.ProductGroups, "ProductGroupId", "Name", product.ProductGroupId);
            ViewBag.PromotionId = new SelectList(db.Promotions, "PromotionId", "Name", product.PromotionId);
            return View(product);
        }

        //// POST: Products1/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit([Bind(Include = "ProductId,ProductGroupId,ManufacturerId,Name,Description,ImportPrice,Price,Status,PromotionId,Amount,Point,GuaranteeProductId,MainPhoto1,MainPhoto2,MainPhoto3,SecondaryPhoto1,SecondaryPhoto2,SecondaryPhoto3,Color,CreatedDate")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GuaranteeProductId = new SelectList(db.GuaranteeProducts, "GuaranteeProductId", "Description", product.GuaranteeProductId);
            ViewBag.ManufacturerId = new SelectList(db.Manufacturers, "ManufacturerId", "Name", product.ManufacturerId);
            ViewBag.ProductGroupId = new SelectList(db.ProductGroups, "ProductGroupId", "Name", product.ProductGroupId);
            ViewBag.PromotionId = new SelectList(db.Promotions, "PromotionId", "Name", product.PromotionId);
            return View(product);
        }

        // GET: Products1/Delete/5
        [HttpPost]
        public JsonResult DeleteProduct(int Id)
        {
            bool result = false;
            Product product = db.Products.Find(Id);
            db.Products.Remove(product);
            db.SaveChanges();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        // POST: Products1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShopHungVuong.Web/Views/Products1/Create.cshtml
@model DataAccess.Models.Product

@{
	ViewBag.Title = "Create";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

<div class="form-horizontal">
	<h4>Product</h4>
	<hr />
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
	<div class="form-group">
		@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.ImportPrice, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.ImportPrice, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.ImportPrice, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			<div class="checkbox">
				@Html.EditorFor(model => model.Status)
				@Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
			</div>
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.MainPhoto1, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-5">
			@Html.EditorFor(model => model.MainPhoto1, new { htmlAttributes = new { @class = "form-control", @value = "model.MainPhoto1", @name = "picture", @id = "picture" } })
			@Html.ValidationMessageFor(model => model.MainPhoto1, "", new { @class = "text-danger" })
		</div>
		<div class="col-md-5">
			<input type="file" id="fileUpload" accept="assets/images/products/*" name="fileUpload" style="display:none;" />
			<input type="button" id="btnUpload" value="Chọn ảnh" class="btn btn-success" />
		</div>
	</div>
	<div class="form-group">
		@Html.LabelFor(model => model.MainPhoto2, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-5">
			@Html.EditorFor(model => model.MainPhoto2, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.MainPhoto2, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.MainPhoto3, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-5">
			@Html.EditorFor(model => model.MainPhoto3, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.MainPhoto3, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.SecondaryPhoto1, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-5">
			@Html.EditorFor(model => model.SecondaryPhoto1, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.SecondaryPhoto1, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.SecondaryPhoto2, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-5">
			@Html.EditorFor(model => model.SecondaryPhoto2, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.SecondaryPhoto2, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.SecondaryPhoto3, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-5">
			@Html.EditorFor(model => model.SecondaryPhoto3, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.SecondaryPhoto3, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-5">
			@Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Point, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Point, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Point, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.ProductGroupId, "ProductGroupId", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.DropDownList("ProductGroupId", null, htmlAttributes: new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.ProductGroupId, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.GuaranteeProductId, "GuaranteeProductId", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.DropDownList("GuaranteeProductId", null, htmlAttributes: new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.GuaranteeProductId, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.PromotionId, "PromotionId", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.DropDownList("PromotionId", null, htmlAttributes: new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.PromotionId, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.ManufacturerId, "ManufacturerId", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.DropDownList("ManufacturerId", null, htmlAttributes: new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.ManufacturerId, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<input type="submit" value="Create" class="btn btn-default" />
		</div>
	</div>
</div>
}

<div>
	@Html.ActionLink("Back to List", "Index")
</div>

<script type="text/javascript">
	$(function () {
		//đăng ký sự kiện click nut btnUpload
		$('#btnUpload').click(function () {
			$('#fileUpload').trigger('click');
		});
		//bắt sự kiện change data của fileUpload
		$('#fileUpload').change(function () {
			//kiểm tra trình duyệt có hỗ trợ form data hay không
			if (window.FormData != undefined) {
				//lấy dữ liệu trên fileUpload
				var fileUpload = $('#fileUpload').get(0);
				var files = fileUpload.files;
				//tạo đối tượng form data
				var formData = new FormData();
				//đưa dữ liệu vào form
				formData.append('file', files[0]);
				$.ajax({
					type: 'POST',
					url: '/UploadMedia/UploadProduct',
					contentType: false,
					processData: false,
					data: formData,
					success: function (urlImage) {
						$('#pictureUpload').attr('src', urlImage);
						$('#picture').val(urlImage);
					},
					error: function (err) {
						alert('Có lỗi upload: ' + err.statusText);
					}
				});
			}
		});
	});
</script>

ShopHungVuong.Web/Views/Products1/Details.cshtml
@model DataAccess.Models.Product

@{
	ViewBag.Title = "Create";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div>
	<h4>Product</h4>
	<hr />
	<dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.GuaranteeProduct.Description)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.GuaranteeProduct.Description)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Manufacturer.Name)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Manufacturer.Name)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.ProductGroup.Name)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.ProductGroup.Name)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Promotion.Name)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Promotion.Name)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Name)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Name)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Description)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Description)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.ImportPrice)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.ImportPrice)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Price)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Price)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Status)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Status)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.MainPhoto1)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.MainPhoto1)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.MainPhoto2)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.MainPhoto2)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.MainPhoto3)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.MainPhoto3)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.SecondaryPhoto1)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.SecondaryPhoto1)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.SecondaryPhoto2)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.SecondaryPhoto2)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.SecondaryPhoto3)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.SecondaryPhoto3)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.CreatedDate)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.CreatedDate)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Color)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Color)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Amount)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Amount)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Point)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Point)
		</dd>

	</dl>
</div>
<p>
	@Html.ActionLink("Edit", "Edit", new { id = Model.ProductId }) |
	@Html.ActionLink("Back to List", "Index")
</p>

ShopHungVuong.Web/Views/Products1/Index.cshtml
@model IEnumerable<DataAccess.Models.Product>
@{
	ViewBag.Title = "Tin tức";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<link href="~/dataAdmin/dataTable/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="~/dataAdmin/skins/_all-skins.min.css" rel="stylesheet" />

<section class="content">
	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<div class="col-md-6">
						<h3 class="box-title">Danh sách sản phẩm</h3>
					</div>
					<div class="col-md-6">
						@Html.ActionLink("Thêm sản phẩm", "Create", "Products1", new { @class = "btn btn-success" })
					</div>
				</div>
				<div class="box-body">
					<div id="example1_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
						<div class="row">
						</div>
						<div class="row">
							<div class="col-sm-12">
								<table id="example1" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
									<thead>
										<tr role="row">
											<th style="width:60px">Ảnh</th>
											<th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Tên sản phẩm: activate to sort column ascending" style="width: 300px;">Tên sản phẩm</th>
											<th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Hãn sản xuất: activate to sort column ascending" style="width: 100px;">Hãng sản xuất</th>
											<th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Số lượng còn: activate to sort column ascending" style="width: 100px;">Số lượng còn</th>
											<th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="Loại sản phẩm: activate to sort column ascending" style="width: 50px;">Loại sản phẩm</th>
											<td style="width: 65px;">Tùy chọn</td>
										</tr>
									</thead>
									<tbody>
										@foreach (var item in Model)
										{
										<tr role="row" class="odd" id="row_@item.ProductId">
											<td><img src="~/assets/images/product/@item.MainPhoto1" width="50"/></td>
											<td class="sorting">@item.Name</td>
											<td>@item.Manufacturer.Name</td>
											<td>@item.Amount</td>
											<td>@item.ProductGroup.Name</td>
											<td>
												@Html.ActionLink("Sửa", "Edit", new { id = item.ProductId }, new { @class = "btn btn-success" })
												<a href="#" class="btn btn-danger" onclick="ConfirmDelete(@item.ProductId)">Xóa </a>
											</td>
										</tr>
										}

									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
				<!-- /.box-body -->
			</div>
			<!-- /.box -->
		</div>
		<!-- /.col -->
	</div>
	<!-- /.row -->
</section>
<div class="modal fade" id="myModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<a href="#" class="close" data-dismiss="modal">&times;</a>
				<h3 class="modal-title">Xóa sản phẩm</h3>
			</div>
			<div class="modal-body">
				<h4>Bạn có chắc muốn xóa sản phẩm này </h4>
				<div style="text-align:center;display:none" id="loaderDiv">
				</div>
			</div>
			<div class="modal-footer">
				<a href="#" class="btn btn-default" data-dismiss="modal">Thoát</a>
				<a href="#" class="btn btn-success" onclick="DeleteProduct()">Xác nhận</a>
			</div>
		</div>
	</div>
	<input type="hidden" id="hiddenId" />
</div>

<script>
	var ConfirmDelete = function (Id) {
		$("#hiddenId").val(Id);
		$("#myModal").modal('show');
	}
	var DeleteProduct = function () {
		$("#loaderDiv").show();
		var productId = $("#hiddenId").val();
		$.ajax({
			type: "POST",
			url: "/Products1/DeleteProduct",
			data: { Id: productId },
			success: function (result) {
				$("#loaderDiv").hide();
				$("#myModal").modal("hide");
				$("#row_" + productId).remove();
			}
		})
	}
</script>


<script src="~/dataAdmin/dataTable/jquery.dataTables.min.js"></script>
<script src="~/dataAdmin/dataTable/dataTables.bootstrap.min.js"></script>
<script src="~/dataAdmin/dataTable/demo.js"></script>
<script src="~/dataAdmin/dataTable/fastclick.js"></script>
<script src="~/dataAdmin/dataTable/jquery.slimscroll.min.js"></script>

<script>
		$(function () {
			$('#example1').DataTable()
			$('#example2').DataTable({
				'paging': true,
				'lengthChange': false,
				'searching': false,
				'ordering': true,
				'info': true,
				'autoWidth': false
			})
		})
</script>