ShopHungVuong.Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccess;
using DataAccess.Models;
namespace ShopHungVuong.Web.Controllers
{
    public class AdminController : Controller
    {
        DataContext db = new DataContext();
        // GET: Admin
        public ActionResult Index()
        {
            if (Session["userID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }
        public ActionResult LogOut()
        {
            int userId = (int)Session["userID"];
            Session.Abandon();
            return RedirectToAction("Login", "Home");
        }
        public ActionResult Account()
        {
            User user = db.Users.Find(Session["userID"]);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }
    }
}

ShopHungVuong.Web/Controllers/ArticleController.cs
using DataAccess;
using DataAccess.Dao;
using DataAccess.Models;
using ShopHungVuong.Web.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace ShopHungVuong.Web.Controllers
{
    public class ArticleController : Controller
    {
        private DataContext db = new DataContext();

        //GET: News
        public ActionResult Index()
        {
            if (Session["userID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            List<ArticleModelView> listArticle = db.Articles.Select(x => new ArticleModelView { ArticleId = x.ArticleId, ArticleGroupId = x.ArticleGroupId, Author = x.Author, Detail = x.Detail, Photo = x.Photo, PostDate = x.PostDate, Sumary = x.Sumary, Title = x.Title, ArticleGroupName = x.ArticleGroup.Name }).ToList();
            ViewBag.ArticleList = listArticle;
            return View();
        }
        public ActionResult ArticleTulanh()
        {
            List<ArticleModelView> listArticle = db.Articles.Select(x => new ArticleModelView { ArticleId = x.ArticleId, ArticleGroupId = x.ArticleGroupId, Author = x.Author, Detail = x.Detail, Photo = x.Photo, PostDate = x.PostDate, Sumary = x.Sumary, Title = x.Title, ArticleGroupName = x.ArticleGroup.Name }).Where(x =>x.ArticleGroupId == 2).ToList();
            ViewBag.ArticleList = listArticle;
            return View();
        }
        public ActionResult ArticleDieuhoa()
        {
            List<ArticleModelView> listArticle = db.Articles.Select(x => new ArticleModelView { ArticleId = x.ArticleId, ArticleGroupId = x.ArticleGroupId, Author = x.Author, Detail = x.Detail, Photo = x.Photo, PostDate = x.PostDate, Sumary = x.Sumary, Title = x.Title, ArticleGroupName = x.ArticleGroup.Name }).Where(x => x.ArticleGroupId == 5).ToList();
            ViewBag.ArticleList = listArticle;
            return View();
        }
        public ActionResult ArticleMaygiat()
        {
            List<ArticleModelView> listArticle = db.Articles.Select(x => new ArticleModelView { ArticleId = x.ArticleId, ArticleGroupId = x.ArticleGroupId, Author = x.Author, Detail = x.Detail, Photo = x.Photo, PostDate = x.PostDate, Sumary = x.Sumary, Title = x.Title, ArticleGroupName = x.ArticleGroup.Name }).Where(x => x.ArticleGroupId == 6).ToList();
            ViewBag.ArticleList = listArticle;
            return View();
        }
        public ActionResult ArticleTivi()
        {
            List<ArticleModelView> listArticle = db.Articles.Select(x => new ArticleModelView { ArticleId = x.ArticleId, ArticleGroupId = x.ArticleGroupId, Author = x.Author, Detail = x.Detail, Photo = x.Photo, PostDate = x.PostDate, Sumary = x.Sumary, Title = x.Title, ArticleGroupName = x.ArticleGroup.Name }).Where(x => x.ArticleGroupId == 1).ToList();
            ViewBag.ArticleList = listArticle;
            return View();
        }
        public ActionResult ListArticle()
        {
            List<ArticleModelView> listArticle = db.Articles.Select(x => new ArticleModelView { ArticleId = x.ArticleId, ArticleGroupId = x.ArticleGroupId, Author = x.Author, Detail = x.Detail, Photo = x.Photo, PostDate = x.PostDate, Sumary = x.Sumary, Title = x.Title, ArticleGroupName = x.ArticleGroup.Name }).OrderByDescending(x => x.PostDate).ToList();
            ViewBag.ArticleList = listArticle;
            return View();
        }
     
        public ActionResult RecentPost()
        {
            var recentPost = new List<ArticleModelView>();
            recentPost = db.Articles.Select(x => new ArticleModelView { ArticleId = x.ArticleId, ArticleGroupId = x.ArticleGroupId, Author = x.Author, Detail = x.Detail, Photo = x.Photo, PostDate = x.PostDate, Sumary = x.Sumary, Title = x.Title, ArticleGroupName = x.ArticleGroup.Name }).OrderByDescending(x=> x.PostDate).Take(5).ToList();
            ViewBag.RecentPostList = recentPost;
            return View();
        }
        
        public ActionResult Create()
        {
            if (Session["userID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            ViewBag.ArticleGroupId = new SelectList(db.ArticleGroups, "ArticleGroupId", "Name");
            return View();
        }

        [ValidateInput(false)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ArticleId,ArticleGroupId,Author,Title,Sumary,Photo,Detail,PostDate")] Article article)
        {

            if (ModelState.IsValid)
            {

                db.Articles.Add(article);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ArticleGroupId = new SelectList(db.ArticleGroups, "ArticleGroupId", "Name", article.ArticleGroupId);
            return View(article);
        }
       
        public ActionResult Edit(int? id)
        {
            if (Session["userID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            ViewBag.ArticleGroupId = new SelectList(db.ArticleGroups, "ArticleGroupId", "Name", article.ArticleGroup);
            return View(article);
        }


        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ArticleId,ArticleGroupId,Author,Title,Sumary,Photo,Detail,PostDate")] Article article)
        {
            if (ModelState.IsValid)
            {
                db.Entry(article).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ArticleGroupId = new SelectList(db.ArticleGroups, "ArticleGroupId", "Name", article.ArticleGroupId);
            return View(article);
        }
        public JsonResult Delete(int Id)
        {
            bool result = false;
            Article article = db.Articles.Find(Id);
            db.Articles.Remove(article);
            db.SaveChanges();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article @new = db.Articles.Find(id);
            if (@new == null)
            {
                return HttpNotFound();
            }
            return View(@new);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShopHungVuong.Web/Controllers/ServiceController.cs
using DataAccess;
using DataAccess.Models;
using ShopHungVuong.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopHungVuong.Web.Controllers
{
    public class ServiceController : Controller
    {
        private DataContext db = new DataContext();

        public ActionResult Index()
        {
            if (Session["userID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            List<ServiceModelView> listService = db.Services.Select(x => new ServiceModelView { Id = x.ServicerId, ServiceName = x.ServiceName, Description = x.Description, Price = x.Price, WarrantyPeriod = x.WarrantyPeriod }).ToList();
            ViewBag.ServiceList = listService;
            return View();
        }

        [HttpPost]
        public ActionResult Index(ServiceModelView model)
        {
            try
            {
                List<Service> list = db.Services.ToList();
                if (model.Id > 0)
                {
                    //update
                    Service service = db.Services.SingleOrDefault(x => x.ServicerId == model.Id);
                    service.ServicerId = model.Id;
                    service.ServiceName = model.ServiceName;
                    service.WarrantyPeriod = model.WarrantyPeriod;
                    service.Price = model.Price;
                    service.Description = model.Description;
                    db.SaveChanges();
                }
                else
                {
                    //Insert
                    Service service = new Service
                    {
                        Description = model.Description,
                        Price = model.Price,
                        WarrantyPeriod = model.WarrantyPeriod,
                        ServiceName = model.ServiceName,

                    };
                    db.Services.Add(service);
                    db.SaveChanges();
                }
                return View(model);

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult AddEditService(int Id)
        {
            List<Service> services = db.Services.ToList();
            ServiceModelView model = new ServiceModelView();

            if (Id > 0)
            {

                Service service = db.Services.SingleOrDefault(x => x.ServicerId == Id);
                model.Id = service.ServicerId;
                model.ServiceName = service.ServiceName;
                model.Description = service.Description;
                model.Price = service.Price;
                model.WarrantyPeriod = service.WarrantyPeriod;
            }
            return PartialView("Details", model);
        }


        public JsonResult DeleteService(int Id)
        {
            bool result = false;
            Service Service = db.Services.Find(Id);
            db.Services.Remove(Service);
            db.SaveChanges();
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShopHungVuong.Web/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Admin</title>
	<!-- Tell the browser to be responsive to screen width -->
	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
	@*<link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">*@
	@*<link href="~/dataAdmin/bootstrap.min.css" rel="stylesheet" />*@
	<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
	<!-- Font Awesome -->
	<link rel="stylesheet" href="~/dataAdmin/font-awesome.min.css">
	<!-- Ionicons -->
	<link rel="stylesheet" href="~/dataAdmin/ionicons.min.css">
	<!-- Theme style -->
	<link rel="stylesheet" href="~/dataAdmin/AdminLTE.min.css">
	<link href="~/dataAdmin/skin-blue.min.css" rel="stylesheet" />
	<script src="~/Scripts/jquery-3.3.1.min.js"></script>

	<link rel="stylesheet"
		  href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

<body class="hold-transition skin-blue sidebar-mini">
	<div class="wrapper">

		<!-- Main Header -->
		<header class="main-header">

			<!-- Logo -->
			<a href="index2.html" class="logo">
				<!-- mini logo for sidebar mini 50x50 pixels -->
				<span class="logo-mini"><b>A</b>LT</span>
				<!-- logo for regular state and mobile devices -->
				<span class="logo-lg"><b>Admin</b>LTE</span>
			</a>

			<!-- Header Navbar -->
			<nav class="navbar navbar-static-top" role="navigation">
				<!-- Sidebar toggle button-->
				<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
					<span class="sr-only">Toggle navigation</span>
				</a>
				<!-- Navbar Right Menu -->
				<div class="navbar-custom-menu">
					<ul class="nav navbar-nav">
						<!-- Messages: style can be found in dropdown.less-->
						@*<li class="dropdown messages-menu">
							<!-- Menu toggle button -->
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<i class="fa fa-envelope-o"></i>
								<span class="label label-success">4</span>
							</a>
							<ul class="dropdown-menu">
								<li class="header">You have 4 messages</li>
								<li>
									<!-- inner menu: contains the messages -->
									<ul class="menu">
										<li>
											<!-- start message -->
											<a href="#">
												<div class="pull-left">
													<!-- User Image -->
													<img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
												</div>
												<!-- Message title and timestamp -->
												<h4>
													Support Team
													<small><i class="fa fa-clock-o"></i> 5 mins</small>
												</h4>
												<!-- The message -->
												<p>Why not buy a new awesome theme?</p>
											</a>
										</li>
										<!-- end message -->
									</ul>
									<!-- /.menu -->
								</li>
								<li class="footer"><a href="#">See All Messages</a></li>
							</ul>
						</li>*@
						<!-- /.messages-menu -->
						<!-- Notifications Menu -->
						@*<li class="dropdown notifications-menu">
							<!-- Menu toggle button -->
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<i class="fa fa-bell-o"></i>
								<span class="label label-warning">10</span>
							</a>
							<ul class="dropdown-menu">
								<li class="header">You have 10 notifications</li>
								<li>
									<!-- Inner Menu: contains the notifications -->
									<ul class="menu">
										<li>
											<!-- start notification -->
											<a href="#">
												<i class="fa fa-users text-aqua"></i> 5 new members joined today
											</a>
										</li>
										<!-- end notification -->
									</ul>
								</li>
								<li class="footer"><a href="#">View all</a></li>
							</ul>
						</li>*@
						<!-- Tasks Menu -->
						@*<li class="dropdown tasks-menu">
							<!-- Menu Toggle Button -->
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<i class="fa fa-flag-o"></i>
								<span class="label label-danger">9</span>
							</a>
							<ul class="dropdown-menu">
								<li class="header">You have 9 tasks</li>
								<li>
									<!-- Inner menu: contains the tasks -->
									<ul class="menu">
										<li>
											<!-- Task item -->
											<a href="#">
												<!-- Task title and progress text -->
												<h3>
													Design some buttons
													<small class="pull-right">20%</small>
												</h3>
												<!-- The progress bar -->
												<div class="progress xs">
													<!-- Change the css width attribute to simulate progress -->
													<div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar"
														 aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
														<span class="sr-only">20% Complete</span>
													</div>
												</div>
											</a>
										</li>
										<!-- end task item -->
									</ul>
								</li>
								<li class="footer">
									<a href="#">View all tasks</a>
								</li>
							</ul>
						</li>*@
						<!-- User Account Menu -->
						@Html.Action("Account","Admin")
						<!-- Control Sidebar Toggle Button -->
						<li>
							<a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
						</li>
					</ul>
				</div>
			</nav>
		</header>
		<!-- Left side column. contains the logo and sidebar -->
		<aside class="main-sidebar">

			<!-- sidebar: style can be found in sidebar.less -->
			<section class="sidebar">

				<!-- Sidebar user panel (optional) -->
				@*<div class="user-panel">
					<div class="pull-left image">
						<img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
					</div>
					<div class="pull-left info">
						<p>Alexander Pierce</p>
						
						<a href="#"><i class="fa fa-circle text-success"></i> Online</a>
					</div>
				</div>*@

				<!-- search form (Optional) -->
				<form action="#" method="get" class="sidebar-form">
					<div class="input-group">
						<input type="text" name="q" class="form-control" placeholder="Search...">
						<span class="input-group-btn">
							<button type="submit" name="search" id="search-btn" class="btn btn-flat">
								<i class="fa fa-search"></i>
							</button>
						</span>
					</div>
				</form>
				<!-- /.search form -->
				<!-- Sidebar Menu -->
				<ul class="sidebar-menu" data-widget="tree">
					<li class="header">HEADER</li>
					<!-- Optionally, you can add icons to the links -->

					<li class="active"><a href="@Url.Action("Index","Home")"><i class="fa fa-dashboard"></i> <span>Review</span></a></li>
					@*<li><a href="#"><i class="fa-file-text-o"></i> <span>Tin tức</span></a></li>*@
					<li class="treeview">
						<a href="#">
							<i class="fa fa-file-text-o"></i> <span>Tin tức</span>
							<span class="pull-right-container">
								<i class="fa fa-angle-left pull-right"></i>
							</span>
						</a>
						<ul class="treeview-menu">
							<li><a href="@Url.Action("Index","ArticleGroups")">Nhóm bài viết</a></li>
							<li><a href="@Url.Action("Index","Article")">Bài viết</a></li>
						</ul>
					</li>
					<li class="treeview">
						<a href="#">
							<i class="fa fa-television"></i> <span>Quản lý sản phẩm</span>
							<span class="pull-right-container">
								<i class="fa fa-angle-left pull-right"></i>
							</span>
						</a>
						<ul class="treeview-menu">
							<li><a href="@Url.Action("Index","ArticleGroups")">Nhóm sản phẩm</a></li>
							<li><a href="@Url.Action("Index","Products1")">Danh sách sản phẩm</a></li>
						</ul>
					</li>
					<li><a href="@Url.Action("Index","Manufacturers")"><i class="fa fa-user-circle-o" aria-hidden="true"></i> <span>Nhà sản xuất</span></a></li>
					<li><a href="@Url.Action("Index","Service")"><i class="fa fa-truck" aria-hidden="true"></i> <span>Dịch vụ</span></a></li>
					<li><a href="@Url.Action("Index","Promotions")"><i class="fa fa-percent" aria-hidden="true"></i> <span>Chương trình khuyến mại</span></a></li>
					<li><a href="@Url.Action("Index","GuaranteeProduct")"><i class="fa fa-undo" aria-hidden="true"></i> <span>Chương trình bảo hành</span></a></li>
					<li><a href="@Url.Action("Index","OrderRepairs")"><i class="fa fa-users" aria-hidden="true"></i> <span>Quản lý đặt lịch</span></a></li>
				</ul>
				<!-- /.sidebar-menu -->
			</section>
			<!-- /.sidebar -->
		</aside>

		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<!-- Content Header (Page header) -->
			<section class="content-header">
				<h1>
					Trang chủ
					<small>Optional description</small>
				</h1>
				@*<ol class="breadcrumb">
					<li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
					<li class="active">Here</li>
				</ol>*@
			</section>

			<!-- Main content -->
			<section class="content container-fluid">

				@RenderBody()

			</section>
			<!-- /.content -->
		</div>
		<!-- /.content-wrapper -->
		<!-- Main Footer -->
		<footer class="main-footer">
			<!-- To the right -->
			<div class="pull-right hidden-xs">
				Anything you want
			</div>
			<!-- Default to the left -->
			<strong>Copyright &copy; 2016 <a href="#">Company</a>.</strong> All rights reserved.
		</footer>

		<!-- Control Sidebar -->
		<aside class="control-sidebar control-sidebar-dark">
			<!-- Create the tabs -->
			<ul class="nav nav-tabs nav-justified control-sidebar-tabs">
				<li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
				<li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
			</ul>
			<!-- Tab panes -->
			<div class="tab-content">
				<!-- Home tab content -->
				<div class="tab-pane active" id="control-sidebar-home-tab">
					<h3 class="control-sidebar-heading">Recent Activity</h3>
					<ul class="control-sidebar-menu">
						<li>
							<a href="javascript:;">
								<i class="menu-icon fa fa-birthday-cake bg-red"></i>

								<div class="menu-info">
									<h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

									<p>Will be 23 on April 24th</p>
								</div>
							</a>
						</li>
					</ul>
					<!-- /.control-sidebar-menu -->

					<h3 class="control-sidebar-heading">Tasks Progress</h3>
					<ul class="control-sidebar-menu">
						<li>
							<a href="javascript:;">
								<h4 class="control-sidebar-subheading">
									Custom Template Design
									<span class="pull-right-container">
										<span class="label label-danger pull-right">70%</span>
									</span>
								</h4>

								<div class="progress progress-xxs">
									<div class="progress-bar progress-bar-danger" style="width: 70%"></div>
								</div>
							</a>
						</li>
					</ul>
					<!-- /.control-sidebar-menu -->

				</div>
				<!-- /.tab-pane -->
				<!-- Stats tab content -->
				<div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
				<!-- /.tab-pane -->
				<!-- Settings tab content -->
				<div class="tab-pane" id="control-sidebar-settings-tab">
					<form method="post">
						<h3 class="control-sidebar-heading">General Settings</h3>

						<div class="form-group">
							<label class="control-sidebar-subheading">
								Report panel usage
								<input type="checkbox" class="pull-right" checked>
							</label>

							<p>
								Some information about this general settings option
							</p>
						</div>
						<!-- /.form-group -->
					</form>
				</div>
				<!-- /.tab-pane -->
			</div>
		</aside>
		<!-- /.control-sidebar -->
		<!-- Add the sidebar's background. This div must be placed
		immediately after the control sidebar -->
		<div class="control-sidebar-bg"></div>
	</div>
	@*<script src="~/dataAdmin/jquery.min.js"></script>*@
	@*<script src="~/dataAdmin/bootstrap.min.js"></script>*@
	<script src="~/Scripts/bootstrap.min.js"></script>
	<script src="~/dataAdmin/adminlte.min.js"></script>

	@RenderSection("scripts", required: false)
	@RenderSection("datascript", required: false)
	@RenderSection("editscript", required: false)
	
</body>
</html>

ShopHungVuong.Web/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<title>DIEN TU HUNG VUONG</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Favicon -->
	<link rel="shortcut icon" type="image/x-icon" href="~/assets/images/favicon.ico">

	<!-- CSS
	============================================ -->
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="~/assets/css/bootstrap.min.css">

	<!-- Icon Font CSS -->
	<link rel="stylesheet" href="~/assets/css/icon-font.min.css">

	<!-- Plugins CSS -->
	<link rel="stylesheet" href="~/assets/css/plugins.css">

	<!-- Main Style CSS -->
	<link rel="stylesheet" href="~/assets/css/style.css">

	<!-- Modernizer JS -->
	<script src="~/assets/js/vendor/modernizr-2.8.3.min.js"></script>
</head>

<body>
	@Html.Action("MainHeader", "Home")

	@RenderBody()

	@Html.Action("MainFooter", "Home")

	<script src="~/assets/js/vendor/jquery-1.12.4.min.js"></script>
	<!-- Popper JS -->
	<script src="~/assets/js/popper.min.js"></script>
	<!-- Bootstrap JS -->
	<script src="~/assets/js/bootstrap.min.js"></script>
	<!-- Plugins JS -->
	<script src="~/assets/js/plugins.js"></script>
	<!-- Main JS -->
	<script src="~/assets/js/main.js"></script>


</body>

</html>